# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-07 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
        ('lookup', '0001_initial'),
        ('bakround_applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SME',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('review_limit', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('ask_about_low_scores', models.BooleanField(default=True)),
                ('employer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employer.EmployerUser')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakround_applicant.Job')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lookup.LookupRegion')),
            ],
            options={
                'db_table': 'sme',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SMEAction',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_name', models.CharField(max_length=50)),
                ('profile_resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakround_applicant.ProfileResume')),
                ('sme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sme_feedback.SME')),
            ],
            options={
                'db_table': 'sme_action',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SMEFeedback',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bscore_value', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('comment', models.CharField(max_length=10000)),
                ('should_interview', models.BooleanField()),
                ('wrong_job', models.NullBooleanField(db_index=True)),
                ('wrong_language', models.NullBooleanField(db_index=True)),
                ('incomplete', models.NullBooleanField(db_index=True)),
                ('insuff_exp', models.NullBooleanField()),
                ('insuff_skills', models.NullBooleanField()),
                ('insuff_certs', models.NullBooleanField()),
                ('unknown_employers', models.NullBooleanField()),
                ('unknown_schools', models.NullBooleanField()),
                ('feedback_guid', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('profile_resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakround_applicant.ProfileResume')),
                ('sme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sme_feedback.SME')),
            ],
            options={
                'db_table': 'sme_feedback',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SMEPayRate',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pay_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sme_feedback.SME')),
            ],
            options={
                'db_table': 'sme_pay_rate',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='smefeedback',
            name='sme_pay_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sme_feedback.SMEPayRate'),
        ),
    ]
