image: alpine:latest
pipelines:
  branches:
    master:
      - step:
          name: deploy
          services:
            - docker
          script:
            - apk add --no-cache --repository http://dl-2.alpinelinux.org/alpine/edge/main nodejs-current-npm
            - apk add --no-cache python3 git
            - python3 -m ensurepip
            - pip3 install --upgrade pip setuptools
            - if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip; fi
            - if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi
            - pip3 install boto3
            - ./scripts/deploy/deploy.sh
options:
  docker: true
definitions:
  services:
    docker:
      memory: 3072
