version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}
services:
  db:
    build: ./compose/local/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    env_file:
      - ./compose/common/local_env
    ports:
      - "15432:5432"
  redis:
    image: redis:5.0.0-alpine
    ports:
        - "6379"
  rabbitmq:
    hostname: rabbitmq
    build: ./compose/local/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - db
    env_file:
      - ./compose/common/local_env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - db
      - redis
      - rabbitmq
    privileged: true
  worker:
    build:
      context: .
      dockerfile: ./compose/worker/Dockerfile
    depends_on:
      - rabbitmq
    env_file:
      - ./compose/common/local_env
    volumes:
      - .:/app
    links:
      - db
      - redis
      - rabbitmq
