# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-07 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bakround_applicant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0001_initial'),
        ('onet', '0001_initial'),
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationrecipientevent',
            name='notification_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.NotificationRecipient'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.Notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='initiator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_recipients', to='bakround_applicant.Profile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_senders', to='bakround_applicant.Profile'),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.Job'),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.Skill'),
        ),
        migrations.AddField(
            model_name='jobremapaudit',
            name='from_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_job', to='bakround_applicant.Job'),
        ),
        migrations.AddField(
            model_name='jobremapaudit',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.Profile'),
        ),
        migrations.AddField(
            model_name='jobremapaudit',
            name='to_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_job', to='bakround_applicant.Job'),
        ),
        migrations.AddField(
            model_name='jobcertification',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakround_applicant.Certification'),
        ),
        migrations.AddField(
            model_name='jobcertification',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakround_applicant.Job'),
        ),
        migrations.AddField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employer.Employer'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.JobFamily'),
        ),
        migrations.AddField(
            model_name='job',
            name='onet_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='onet.BgPositionMaster'),
        ),
        migrations.AddField(
            model_name='job',
            name='parent_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.Job'),
        ),
        migrations.AddField(
            model_name='industryjobfamily',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.LookupIndustry'),
        ),
        migrations.AddField(
            model_name='industryjobfamily',
            name='job_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakround_applicant.JobFamily'),
        ),
        migrations.AddField(
            model_name='certification',
            name='parent_certification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.Certification'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipientevent',
            index=models.Index(fields=['action', 'email'], name='notificatio_action_33a53d_idx'),
        ),
    ]
