# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-17 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0003_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileresume',
            name='sovren_output',
        ),
        migrations.RemoveField(
            model_name='profileresume',
            name='sovren_parsed_text_length',
        ),
    ]
