# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-25 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0004_auto_20180717_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileresume',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='profileresume',
            name='cloned_profile_resume',
        ),
        migrations.AddField(
            model_name='profiledetail',
            name='from_profile_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.ProfileResume'),
        ),
        migrations.RemoveField(
            model_name='profiledetail',
            name='indeed_parser_used',
        ),
        migrations.RemoveField(
            model_name='profileresume',
            name='parser_name',
        ),
        migrations.AddField(
            model_name='profileresume',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='FailedQueueMessage',
        ),
    ]
