# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-14 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0007_auto_20180814_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileexperience',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileexperience',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileexperience',
            name='position_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
