# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-14 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0008_auto_20180814_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certification_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certification_name',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='profileresume',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileresume',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileskill',
            name='skill_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
