# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-14 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0009_auto_20180814_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecertification',
            name='certification_name',
            field=models.TextField(),
        ),
    ]
