# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-28 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0011_profileemail_profilephonenumber_profilereverselookup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVerificationRequest',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('callback_queue', models.TextField(blank=True, null=True)),
                ('callback_message', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakround_applicant.Profile')),
            ],
            options={
                'db_table': 'profile_verification_request',
                'managed': True,
            },
        ),
    ]
