# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-29 14:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0012_profileverificationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileresume',
            name='application_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
        migrations.AlterField(
            model_name='profilereverselookup',
            name='provider',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='profileemail',
            index=models.Index(fields=['value'], name='bakround_ap_value_99a97a_idx'),
        ),
        migrations.AddIndex(
            model_name='profilephonenumber',
            index=models.Index(fields=['value'], name='bakround_ap_value_0cce02_idx'),
        ),
    ]
