# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-06 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0014_profileverificationrequest_use_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileverificationrequest',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
