# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-24 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0015_profileverificationrequest_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileverificationrequest',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileverificationrequest',
            name='lookup_performed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileverificationrequest',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
