# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-25 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0016_auto_20180924_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileverificationrequest',
            name='pending_action',
            field=models.BooleanField(default=False),
        ),
    ]
