# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-04 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0017_profileverificationrequest_pending_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileverificationrequest',
            name='broken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileverificationrequest',
            name='unreachable',
            field=models.BooleanField(default=False),
        ),
    ]
