# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-11 21:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0018_auto_20181004_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalResponse',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recieved', models.DateTimeField(db_index=True)),
                ('from_email', models.TextField(null=True)),
                ('to_email', models.TextField(null=True)),
                ('body', models.TextField(null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('source', models.TextField(db_index=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'external_response',
                'managed': True,
            },
        ),
    ]
