# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-16 20:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0019_externalresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileverificationrequest',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
