# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-18 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0020_profileverificationrequest_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalresponse',
            old_name='recieved',
            new_name='received',
        ),
    ]
