# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-23 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_auto_20181023_2003'),
        ('bakround_applicant', '0022_fix_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledetail',
            name='from_profile_resume',
        ),
        migrations.RemoveField(
            model_name='profiledetail',
            name='profile',
        ),
        migrations.DeleteModel(
            name='ProfileDetail',
        ),
    ]
