# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-02 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0023_auto_20181023_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileexternaldata',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='profileexternaldata',
            name='profile',
        ),
        migrations.DeleteModel(
            name='ProfileExternalData',
        ),
    ]
