# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-06 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0024_auto_20181102_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileJobMapping',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.Job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.Profile')),
            ],
            options={
                'db_table': 'profile_job_mapping',
                'managed': True,
            },
        ),
    ]
