# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-06 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0025_profilejobmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobremapaudit',
            name='from_job',
        ),
        migrations.RemoveField(
            model_name='jobremapaudit',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='jobremapaudit',
            name='to_job',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gh_unique_id',
        ),
        migrations.DeleteModel(
            name='JobRemapAudit',
        ),
    ]
