# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-29 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_icimsapplicantworkflowdata_assessment_update_url'),
        ('bakround_applicant', '0026_auto_20181106_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcimsProfileJobMapping',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('icims_job_data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ranking.IcimsJobData')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.Job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.Profile')),
            ],
            options={
                'db_table': 'icims_profile_job_mapping',
                'managed': True,
            },
        ),
    ]
