# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-29 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0027_icimsprofilejobmapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icimsprofilejobmapping',
            old_name='icims_job_data',
            new_name='icims_job_id',
        ),
    ]
