# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-07 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookupCandidateStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=256)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lookup_candidate_status',
            },
        ),
        migrations.CreateModel(
            name='LookupCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=30, null=True)),
                ('country_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Lookup countries',
                'db_table': 'lookup_country',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupDeclineReason',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=256)),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'lookup_decline_reason',
            },
        ),
        migrations.CreateModel(
            name='LookupDegreeMajor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('degree_major_name', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'db_table': 'lookup_degree_major',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupDegreeName',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('degree_name', models.CharField(blank=True, max_length=128)),
                ('degree_abbreviation', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'lookup_degree_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupDegreeType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('degree_type_name', models.CharField(blank=True, max_length=50)),
                ('degree_type_sovren', models.CharField(blank=True, max_length=50, null=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lookup_degree_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupIndustry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('industry_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'lookup_industry',
            },
        ),
        migrations.CreateModel(
            name='LookupPhysicalLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(db_index=True, max_length=1000)),
                ('latitude', models.FloatField(db_index=True, null=True)),
                ('longitude', models.FloatField(db_index=True, null=True)),
            ],
            options={
                'db_table': 'lookup_physical_location',
            },
        ),
        migrations.CreateModel(
            name='LookupRegion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True)),
                ('city', models.CharField(max_length=1000)),
                ('radius', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'lookup_region',
            },
        ),
        migrations.CreateModel(
            name='LookupRejectReason',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=256)),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'lookup_reject_reason',
            },
        ),
        migrations.CreateModel(
            name='LookupState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(blank=True, max_length=30, null=True)),
                ('state_name', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lookup.LookupCountry')),
            ],
            options={
                'db_table': 'lookup_state',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupZipCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zip_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('city', models.CharField(db_index=True, max_length=128)),
                ('latitude', models.FloatField(db_index=True, null=True)),
                ('longitude', models.FloatField(db_index=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.LookupState')),
            ],
            options={
                'db_table': 'lookup_zip_code',
            },
        ),
        migrations.AddField(
            model_name='lookupregion',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.LookupState'),
        ),
        migrations.AddField(
            model_name='lookupphysicallocation',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lookup.LookupState'),
        ),
        migrations.AddField(
            model_name='lookupdegreename',
            name='degree_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lookup.LookupDegreeType'),
        ),
    ]
