# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 16:28
from __future__ import unicode_literals

from django.db import migrations
from bakround_applicant.utilities.migrations import insert_migration_data

class Migration(migrations.Migration):
    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_migration_data('lookup')),
    ]
