# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-28 14:58
from __future__ import unicode_literals

import os
from django.conf import settings
from django.db import migrations
from bakround_applicant.utilities.migrations import insert_migration_data

# sql_statements = """
# UPDATE bg_alternate_titles
# SET
# onet_id = '656'
# WHERE
# onet_id = '902'
# and
# alt_title = 'Director of Nursing (DON)';

# UPDATE bg_alternate_titles
# SET
# onet_id = '656',
# alt_title = 'Associate Director of Nursing (ADON)'
# WHERE
# onet_id = '12'
# and
# alt_title = 'Associate Director of Nursing';

# UPDATE bg_alternate_titles
# SET
# alt_title = 'Nurse Practitioner (NP)'
# WHERE
# onet_id = '736'
# and
# alt_title = 'Nurse Practitioner';


# UPDATE bg_alternate_titles
# SET
# alt_title = 'Family Nurse Practitioner (FNP)'
# WHERE
# onet_id = '736'
# and
# alt_title = 'Family Nurse Practitioner';


# UPDATE bg_alternate_titles
# SET
# alt_title = 'Certified Nurse Practitioner (CNP)'
# WHERE
# onet_id = '736'
# and
# alt_title = 'Certified Nurse Practitioner';


# UPDATE bg_alternate_titles
# SET
# alt_title = 'Certified Registered Nurse Practitioner (CRNP)'
# WHERE
# onet_id = '736'
# and
# alt_title = 'Certified Registered Nurse Practitioner';
# """

# filename = os.path.join(str(settings.APPS_DIR), "../migration_data/onet/onet.sql")
# with open(filename) as f:
#     sql_statements = f.read() + ";" + sql_statements

class Migration(migrations.Migration):
    dependencies = [
        ('onet', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_migration_data('onet')),
        #migrations.RunSQL(sql_statements),
    ]
