# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-07 20:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bakround_applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(max_length=512, unique=True)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.Job')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.Profile')),
            ],
            options={
                'db_table': 'scraper',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScraperJob',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('login_url', models.CharField(max_length=512)),
                ('start_url', models.CharField(max_length=512, unique=True)),
                ('start_page', models.IntegerField(blank=True, null=True)),
                ('end_page', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('always_use_hireability', models.BooleanField(default=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.Job')),
            ],
            options={
                'db_table': 'scraper_job',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScraperLogin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('use_for_name_verification', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'scraper_login',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='scraper',
            name='scraper_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scraping.ScraperJob'),
        ),
    ]
