# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-16 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperjob',
            name='always_use_hireability',
            field=models.BooleanField(default=False),
        ),
    ]
