# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-17 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20180716_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperjob',
            name='always_use_hireability',
        ),
        migrations.AddField(
            model_name='scraperjob',
            name='parser',
            field=models.CharField(choices=[('indeed_only', 'Indeed Parser'), ('hireability', 'HireAbility Parser'), ('indeed_with_hireability_fallback', 'Indeed Parser (with HireAbility fallback)')], default='indeed_only', max_length=32),
        ),
    ]
