# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-29 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20180717_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperjob',
            name='parser',
        ),
    ]
