# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-04 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_remove_scraperjob_parser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraper',
            name='job',
        ),
        migrations.RemoveField(
            model_name='scraper',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='scraper',
            name='scraper_job',
        ),
        migrations.RenameField(
            model_name='scraperlogin',
            old_name='use_for_name_verification',
            new_name='has_security_clearance',
        ),
        migrations.RemoveField(
            model_name='scraperjob',
            name='login_url',
        ),
        migrations.RemoveField(
            model_name='scraperjob',
            name='source',
        ),
        migrations.AddField(
            model_name='scraperjob',
            name='new_resumes_scraped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scraperjob',
            name='resumes_rescraped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scraperlogin',
            name='adjusted_failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Scraper',
        ),
    ]
