# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-09 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_auto_20180804_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperjob',
            name='start_page',
        ),
        migrations.AddField(
            model_name='scraperjob',
            name='start_offset',
            field=models.IntegerField(default=0),
        ),
    ]
