# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-28 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0008_auto_20180817_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperjob',
            name='completed',
        ),
        migrations.AddField(
            model_name='scraperjob',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
