# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-07 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerTrial',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trial_days', models.IntegerField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employer.Employer')),
            ],
            options={
                'db_table': 'employer_trial',
            },
        ),
        migrations.CreateModel(
            name='LookupPlanLimit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100)),
                ('action_name', models.CharField(max_length=255)),
                ('limit', models.IntegerField()),
            ],
            options={
                'db_table': 'lookup_plan_limit',
            },
        ),
    ]
