# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 23:02
from __future__ import unicode_literals

from django.db import migrations
from bakround_applicant.utilities.migrations import insert_migration_data

# ADD_TRIAL_LIMITS = """
# INSERT INTO lookup_plan_limit(plan_name, action_name, "limit")
#     VALUES
#         ('bestfit-trial', 'employer_user_create', 0),
#         ('bestfit-trial', 'employer_job_candidate_contact', 15);
# """

class Migration(migrations.Migration):
    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        #migrations.RunSQL(ADD_TRIAL_LIMITS)
        migrations.RunPython(insert_migration_data('usage'))
    ]
