#!/bin/sh
# This should only be run from inside docker-compose.
# To run outside, run:  make coverage

cd bakround_applicant
date > ../autogenerated_coverage_report.txt
pytest --no-migrations --cov=bakround_applicant -p no:sugar --cov-report term-missing \
        >> ../autogenerated_coverage_report.txt

