# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 17:53
from __future__ import unicode_literals

from django.db import migrations
from bakround_applicant.utilities.migrations import insert_migration_data

class Migration(migrations.Migration):
    dependencies = [
        ('employer', '0002_auto_20180707_1351'),
    ]

    operations = [
        migrations.RunPython(insert_migration_data("employer")),
    ]
