# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-04 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employercandidate',
            name='guid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=50, null=True, unique=True),
        ),
    ]
