# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-07 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bakround_applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score_value', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('algorithm_version', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.Job')),
                ('profile_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.ProfileDetail')),
            ],
            options={
                'db_table': 'score',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScoreRequest',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_generated', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.Job')),
                ('profile_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.ProfileDetail')),
                ('score', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='score.Score')),
            ],
            options={
                'db_table': 'score_request',
                'managed': True,
            },
        ),
    ]
