# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-22 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakround_applicant', '0021_auto_20181018_1703'),
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.Profile'),
        ),
        migrations.AddField(
            model_name='scorerequest',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bakround_applicant.Profile'),
        ),
    ]
