# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-04 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICIMSApplicantWorkflowData',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('workflow_id', models.BigIntegerField()),
                ('workflow_url', models.CharField(max_length=255)),
                ('person_id', models.BigIntegerField()),
                ('person_name', models.CharField(max_length=255)),
                ('person_url', models.CharField(max_length=255)),
                ('job_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_arranged', models.BooleanField(default=False)),
                ('is_scored', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'icims_applcnt_workflow_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ICIMSLastUpdatedDate',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated_date', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'icims_last_updated_date',
                'managed': True,
            },
        ),
    ]
