# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-10 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_rankingjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icimsapplicantworkflowdata',
            name='is_arranged',
        ),
    ]
