# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-17 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_remove_icimsapplicantworkflowdata_is_arranged'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingjob',
            name='start_offset',
            field=models.IntegerField(default=0),
        ),
    ]
