# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-18 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_rankingjob_start_offset'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcimsJobData',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_link', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'icims_job_data',
                'managed': True,
            },
        ),
    ]
